#!/usr/bin/perl
use File::Temp;
#use IO::Handle;
#STDIN->autoflush(1);
foreach $i (<>) {
  ($m,$d)=$i=~/^(.*?):(.*)/sig;
  $machines{$m}++;
  $line{$m}++;
  $data{"$m"}.="$d";
}
@keys=sort keys %machines;
$count=@keys;
for (my $i=0;$i<$count;$i++) {
  for (my $j=$i+1;$j<$count;$j++) {
    $k1=$keys[$i];
    $k2=$keys[$j];
    $v1=$data{$k1};
    $v2=$data{$k2};
    if ($v1 eq $v2) {
        $matchcnt[$i]++;
        $matchcnt[$j]++;
        $matchKey[$i].="$j~";
        $matchKey[$j].="$i~";
    }
  }
}
$max=0;
$maxKey=-1;
foreach $i (0..@matchcnt) {
        if ($matchcnt[$i]>$max) {
                $max=$matchcnt[$i];
                $maxKey=$i;
        }
}
if ($max==0) {
        # there were no matches, each unique, force first
        print "There are no match, showing first and deltas\n";
        $max=1;
        $maxKey=0;
        $matchKey[0]="~$keys[0]";
}
print "$maxKey had the most Matches with $max\n";
(@k)=split('~',$matchKey[$maxKey]);
print "These machines all match ***************************\n";
foreach $t (@k) {
        print "*  $keys[$t]\n";
        $done{$keys[$t]}=1;
        $done[$t]=1;
}
print "**********This is the data from the matches**********\n";
print "$data{$keys[@k[0]]}";
print "**********End of data from the matches***************\n";
($fh, $name) = mkstemp("tmpfileXXXXX");
print $fh $data{$keys[@k[0]]};
foreach $t (sort keys %data) {
        if ($done{$t}!=1) {
                ($fh2, $name2) = mkstemp("tmpfileXXXXX");
                print "\n********Deltas for $t*****************\n";
                print $fh2 "$data{$t}";
                print `diff $name $name2`;
                `rm $name2`;
                print "********End of deltas for $t**********\n";
        }
}
`rm $name`;

